export const cardData = [
  {
    "id": 1,
    "front": "秋の田の仮庵の庵の苫をあらみ",
    "back": "わが衣手は露にぬれつつ",
    "frontKana": "あきのたのかりほのいほのとまをあらみ",
    "backKana": "わかころもてはつゆにぬれつつ",
    "imageFront": "https://www.ogurasansou.co.jp/site/hyakunin/asset/image/uta001.png",
    "imageBack": "https://www.ogurasansou.co.jp/site/hyakunin/asset/image/uta001.png",
    "audio": "Cardaudio1",
    "author": "天智天皇",
    "theme": "秋",
    "kimarijiFront": 3,
    "kimarijiBack": 7
  },
  {
    "id": 2,
    "front": "春過ぎて夏来にけらし白妙の",
    "back": "衣ほすてふ天の香具山",
    "frontKana": "はるすきてなつきにけらししろたへの",
    "backKana": "ころもほすてふあまのかくやま",
    "imageFront": "",
    "imageBack": "",
    "audio": "Cardaudio2",
    "author": "持統天皇",
    "theme": "夏",
    "kimarijiFront": 3,
    "kimarijiBack": 4
  },
  {
    "id": 3,
    "front": "あしびきの山鳥の尾のしだり尾の",
    "back": "ながながし夜をひとりかもねむ",
    "frontKana": "あしひきのやまとりのをのしたりをの",
    "backKana": "なかなかしよをひとりかもねむ",
    "imageFront": "",
    "imageBack": "",
    "audio": "Cardaudio2",
    "author": "柿本人麿",
    "theme": "恋",
    "kimarijiFront": 2,
    "kimarijiBack": 3
  },
  {
    "id": 4,
    "front": "田子の浦に打ち出でてみれば白妙の",
    "back": "富士の高嶺に雪はふりつつ",
    "frontKana": "たこのうらにうちいててみれはしろたへの",
    "backKana": "ふしのたかねにゆきはふりつつ",
    "imageFront": "",
    "imageBack": "",
    "audio": "Cardaudio2",
    "author": "山辺赤人",
    "theme": "冬",
    "kimarijiFront": 2,
    "kimarijiBack": 2
  },
  {
    "id": 5,
    "front": "奥山に紅葉ふみわけ鳴く鹿の",
    "back": "声きく時ぞ秋は悲しき",
    "frontKana": "おくやまにもみちふみわけなくしかの",
    "backKana": "こゑきくときそあきはかなしき",
    "imagefront": "",
    "imageBack": "",
    "audio": "Cardaudio2",
    "author": "猿丸大夫",
    "theme": "秋",
    "kimarijiFront": 2,
    "kimarijiBack": 2
  },
  {
    "id": 6,
    "front": "鵲の渡せる橋に置く霜の",
    "back": "白きを見れば夜ぞ更けにける",
    "frontKana": "かささきのわたせるはしにおくしもの",
    "backKana": "しろきをみれはよそふけにける",
    "imagefront": "",
    "imageBack": "",
    "audio": "Cardaudio2",
    "author": "中納言家持",
    "theme": "冬",
    "kimarijiFront": 2,
    "kimarijiBack": 2
  },
  {
    "id": 7,
    "front": "天の原ふりさけ見れば春日なる",
    "back": "三笠の山に出でし月かも",
    "frontKana": "あまのはらふりさけみれはかすかなる",
    "backKana": "みかさのやまにいてしつきかも",
    "imagefront": "",
    "imageBack": "",
    "audio": "Cardaudio2",
    "author": "安倍仲麿",
    "theme": "羇旅",
    "kimarijiFront": 3,
    "kimarijiBack": 2
  },
  {
    "id": 8,
    "front": "わが庵は都の辰巳しかぞ住む",
    "back": "世をうぢ山と人はいふなり",
    "frontKana": "わかいほはみやこのたつみしかそすむ",
    "backKana": "よをうちやまとひとはいふなり",
    "imagefront": "",
    "imageBack": "",
    "audio": "Cardaudio2",
    "author": "喜撰法師",
    "theme": "雑",
    "kimarijiFront": 3,
    "kimarijiBack": 3
  },
  {
    "id": 9,
    "front": "花の色は移りにけりないたづらに",
    "back": "わが身世にふるながめせしまに",
    "frontKana": "はなのいろはうつりにけりないたつらに",
    "backKana": "わかみよにふるなかめせしまに",
    "imagefront": "",
    "imageBack": "",
    "audio": "Cardaudio2",
    "author": "小野小町",
    "theme": "春",
    "kimarijiFront": 3,
    "kimarijiBack": 4
  },
  {
    "id": 10,
    "front": "これやこの行くも帰るも別れては",
    "back": "知るも知らぬもあふ坂の関",
    "frontKana": "これやこのゆくもかへるもわかれては",
    "backKana": "しるもしらぬもあふさかのせき",
    "imagefront": "",
    "imageBack": "",
    "audio": "Cardaudio2",
    "author": "蝉丸",
    "theme": "雑",
    "kimarijiFront": 2,
    "kimarijiBack": 2
  },
  {
    "id": 11,
    "front": "わたの原八十島かけて漕ぎ出でぬと",
    "back": "人には告げよ海人の釣船",
    "frontKana": "わたのはらやそしまかけてこきいてぬと",
    "backKana": "ひとにはつけよあまのつりふね",
    "imagefront": "",
    "imageBack": "",
    "audio": "Cardaudio2",
    "author": "参議篁",
    "theme": "羇旅",
    "kimarijiFront": 6,
    "kimarijiBack": 4
  },
  {
    "id": 12,
    "front": "天つ風雲の通ひ路吹きとぢよ",
    "back": "乙女の姿しばしとどめむ",
    "frontKana": "あまつかせくものかよひちふきとちよ",
    "backKana": "をとめのすかたしはしととめむ",
    "imagefront": "",
    "imageBack": "",
    "audio": "Cardaudio2",
    "author": "僧正遍昭",
    "theme": "雑",
    "kimarijiFront": 3,
    "kimarijiBack": 1
  },
  {
    "id": 13,
    "front": "筑波嶺の峰より落つるみなの川",
    "back": "恋ぞ積もりて淵となりぬる",
    "frontKana": "つくはねのみねよりおつるみなのかわ",
    "backKana": "こひそつもりてふちとなりぬる",
    "imagefront": "",
    "imageBack": "",
    "audio": "Cardaudio2",
    "author": "陽成院",
    "theme": "恋",
    "kimarijiFront": 2,
    "kimarijiBack": 3
  },
  {
    "id": 14,
    "front": "陸奥のしのぶもぢずりたれゆえに",
    "back": "乱れそめにしわれならなくに",
    "frontKana": "みちのくのしのふもちすりたれゆゑに",
    "backKana": "みたれそめにしわれならなくに",
    "imagefront": "",
    "imageBack": "",
    "audio": "Cardaudio2",
    "author": "河原左大臣",
    "theme": "恋",
    "kimarijiFront": 2,
    "kimarijiBack": 4
  },
  {
    "id": 15,
    "front": "君がため春の野に出でて若菜摘む",
    "back": "わが衣手に雪は降りつつ",
    "frontKana": "きみかためはるののにいててわかなつむ",
    "backKana": "わかころもてにゆきはふりつつ",
    "imagefront": "",
    "imageBack": "",
    "audio": "Cardaudio2",
    "author": "光孝天皇",
    "theme": "春",
    "kimarijiFront": 6,
    "kimarijiBack": 7
  },
  {
    "id": 16,
    "front": "立ち別れいなばの山の峰に生ふる",
    "back": "まつとし聞かば今帰り来む",
    "frontKana": "たちわかれいなはのやまのみねにおふる",
    "backKana": "まつとしきかはいまかへりこむ",
    "imagefront": "",
    "imageBack": "",
    "audio": "Cardaudio2",
    "author": "中納言行平",
    "theme": "離別",
    "kimarijiFront": 2,
    "kimarijiBack": 2
  },
  {
    "id": 17,
    "front": "ちはやぶる神代も聞かず竜田川",
    "back": "からくれなゐに水くくるとは",
    "frontKana": "ちはやふるかみよもきかすたつたかは",
    "backKana": "からくれなゐにみつくくるとは",
    "imagefront": "",
    "imageBack": "",
    "audio": "Cardaudio2",
    "author": "在原業平朝臣",
    "theme": "秋",
    "kimarijiFront": 2,
    "kimarijiBack": 2
  },
  {
    "id": 18,
    "front": "住の江の岸に寄る波よるさへや",
    "back": "夢の通ひ路人目よくらむ",
    "frontKana": "すみのえのきしによるなみよるさへや",
    "backKana": "ゆめのかよひちひとめよくらむ",
    "imagefront": "",
    "imageBack": "",
    "audio": "Cardaudio2",
    "author": "藤原敏行朝臣",
    "theme": "恋",
    "kimarijiFront": 1,
    "kimarijiBack": 2
  },
  {
    "id": 19,
    "front": "難波潟短き蘆のふしの間も",
    "back": "逢はでこの世を過ぐしてよとや",
    "frontKana": "なにはかたみしかきあしのふしのまも",
    "backKana": "あはてこのよをすくしてよとや",
    "imagefront": "",
    "imageBack": "",
    "audio": "Cardaudio2",
    "author": "伊勢",
    "theme": "恋",
    "kimarijiFront": 4,
    "kimarijiBack": 3
  },
  {
    "id": 20,
    "front": "わびぬれば今はたおなじ難波なる",
    "back": "みをつくしても逢はむとぞ思ふ",
    "frontKana": "なにはかたみしかきあしのふしのまも",
    "backKana": "あはてこのよをすくしてよとや",
    "imagefront": "",
    "imageBack": "",
    "audio": "Cardaudio2",
    "author": "元良親王",
    "theme": "恋",
    "kimarijiFront": 2,
    "kimarijiBack": 7
  },
  {
    "id": 21,
    "front": "今来むといひしばかりに長月の",
    "back": "有明の月を待ち出でつるかな",
    "frontKana": "いまこむといひしはかりになかつきの",
    "backKana": "ありあけのつきをまちいてつるかな",
    "imagefront": "",
    "imageBack": "",
    "audio": "Cardaudio2",
    "author": "素性法師",
    "theme": "恋",
    "kimarijiFront": 3,
    "kimarijiBack": 2
  },
  {
    "id": 22,
    "front": "吹くからに秋の草木のしをるれば",
    "back": "むべ山風をあらしといふらむ",
    "frontKana": "ふくからにあきのくさきのしをるれは",
    "backKana": "むへやまかせをあらしといふらむ",
    "imagefront": "",
    "imageBack": "",
    "audio": "Cardaudio2",
    "author": "文屋康秀",
    "theme": "秋",
    "kimarijiFront": 1,
    "kimarijiBack": 2
  },
  {
    "id": 23,
    "front": "月見ればちぢにものこそ悲しけれ",
    "back": "わが身ひとつの秋にはあらねど",
    "frontKana": "つきみれはちちにものこそかなしけれ",
    "backKana": "わかみひとつのあきにはあらねと",
    "imagefront": "",
    "imageBack": "",
    "audio": "Cardaudio2",
    "author": "大江千里",
    "theme": "秋",
    "kimarijiFront": 2,
    "kimarijiBack": 4
  },
  {
    "id": 24,
    "front": "このたびは幣も取りあへず手向山",
    "back": "紅葉の錦神のまにまに",
    "frontKana": "このたひはぬさもとりあへすたむけやま",
    "backKana": "もみちのにしきかみのまにまに",
    "imagefront": "",
    "imageBack": "",
    "audio": "Cardaudio2",
    "author": "菅家",
    "theme": "羇旅",
    "kimarijiFront": 2,
    "kimarijiBack": 2
  },
  {
    "id": 25,
    "front": "名にし負はば逢う坂山のさねかずら",
    "back": "人に知られで来るよしもがな",
    "frontKana": "なにしおははあふさかやまのさねかつら",
    "backKana": "ひとにしられてくるよしもかな",
    "imagefront": "",
    "imageBack": "",
    "audio": "Cardaudio2",
    "author": "三条右大臣",
    "theme": "恋",
    "kimarijiFront": 3,
    "kimarijiBack": 4
  },
  {
    "id": 26,
    "front": "小倉山峰の紅葉葉心あらば",
    "back": "いまひとたびのみゆき待たなむ",
    "frontKana": "をくらやまみねのもみちはこころあらは",
    "backKana": "いまひとたひのみゆきまたなむ",
    "imagefront": "",
    "imageBack": "",
    "audio": "Cardaudio2",
    "author": "貞信公",
    "theme": "雑秋",
    "kimarijiFront": 2,
    "kimarijiBack": 8
  },
  {
    "id": 27,
    "front": "みかの原わきて流るるいづみ川",
    "back": "いつ見きとてか恋しかるらむ",
    "frontKana": "みかのはらわきてなかるるいつみかは",
    "backKana": "いつみきとてかこひしかるらむ",
    "imagefront": "",
    "imageBack": "",
    "audio": "Cardaudio2",
    "author": "中納言兼輔",
    "theme": "恋",
    "kimarijiFront": 3,
    "kimarijiBack": 3
  },
  {
    "id": 28,
    "front": "山里は冬ぞ寂しさまさりける",
    "back": "人目も草もかれぬと思へば",
    "frontKana": "やまさとはふゆそさびしさまさりける",
    "backKana": "ひとめもくさもかれぬとおもへは",
    "imagefront": "",
    "imageBack": "",
    "audio": "Cardaudio2",
    "author": "源宗于朝臣",
    "theme": "冬",
    "kimarijiFront": 3,
    "kimarijiBack": 3
  },
  {
    "id": 29,
    "front": "心あてに折らばや折らむ初霜の",
    "back": "置きまどはせる白菊の花",
    "frontKana": "こころあてにおらはやおらむはつしもの",
    "backKana": "おきまとはせるしらきくのはな",
    "imagefront": "",
    "imageBack": "",
    "audio": "Cardaudio2",
    "author": "凡河内躬恒",
    "theme": "秋",
    "kimarijiFront": 4,
    "kimarijiBack": 1
  },
  {
    "id": 30,
    "front": "有明のつれなく見えし別れより",
    "back": "暁ばかり憂きものはなし",
    "frontKana": "ありあけのつれなくみえしわかれより",
    "backKana": "あかつきはかりうきものはなし",
    "imagefront": "",
    "imageBack": "",
    "audio": "Cardaudio2",
    "author": "壬生忠岑",
    "theme": "恋",
    "kimarijiFront": 3,
    "kimarijiBack": 2
  },
  {
    "id": 31,
    "front": "朝ぼらけ有明の月と見るまでに",
    "back": "吉野の里に降れる白雪",
    "frontKana": "あさほらけありあけのつきとみるまてに",
    "backKana": "よしののさとにふれるしらゆき",
    "imagefront": "",
    "imageBack": "",
    "audio": "Cardaudio2",
    "author": "坂上是則",
    "theme": "冬",
    "kimarijiFront": 6,
    "kimarijiBack": 2
  },
  {
    "id": 32,
    "front": "山川に風のかけたるしがらみは",
    "back": "流れもあへぬ紅葉なりけり",
    "frontKana": "やまかはにかせのかけたるしからみは",
    "backKana": "なかれもあへぬもみちなりけり",
    "imagefront": "",
    "imageBack": "",
    "audio": "Cardaudio2",
    "author": "春道列樹",
    "theme": "秋",
    "kimarijiFront": 3,
    "kimarijiBack": 3
  },
  {
    "id": 33,
    "front": "ひさかたの光のどけき春の日に",
    "back": "しづ心なく花の散るらむ",
    "frontKana": "ひさかたのひかりのとけきはるのひに",
    "backKana": "しつこころなくはなのちるらむ",
    "imagefront": "",
    "imageBack": "",
    "audio": "Cardaudio2",
    "author": "紀友則",
    "theme": "春",
    "kimarijiFront": 2,
    "kimarijiBack": 2
  },
  {
    "id": 34,
    "front": "誰をかも知る人にせむ高砂の",
    "back": "松も昔の友ならなくに",
    "frontKana": "たれをかもしるひとにせんたかさごの",
    "backKana": "まつもむかしのともならなくに",
    "imagefront": "",
    "imageBack": "",
    "audio": "Cardaudio2",
    "author": "藤原興風",
    "theme": "雑",
    "kimarijiFront": 2,
    "kimarijiBack": 3
  },
  {
    "id": 35,
    "front": "人はいさ心も知らずふるさとは",
    "back": "花ぞ昔の香に匂ひける",
    "frontKana": "ひとはいさこころもしらすふるさとは",
    "backKana": "はなそむかしのかににほひける",
    "imagefront": "",
    "imageBack": "",
    "audio": "Cardaudio2",
    "author": "紀貫之",
    "theme": "春",
    "kimarijiFront": 3,
    "kimarijiBack": 3
  },
  {
    "id": 36,
    "front": "夏の夜はまだ宵ながら明けぬるを",
    "back": "雲のいずこに月宿るらむ",
    "frontKana": "なつのよはまたよひなからあけぬるを",
    "backKana": "くものいつこにつきやとるらむ",
    "imagefront": "",
    "imageBack": "",
    "audio": "Cardaudio2",
    "author": "清原深養父",
    "theme": "夏",
    "kimarijiFront": 2,
    "kimarijiBack": 3
  },
  {
    "id": 37,
    "front": "白露に風の吹きしく秋の野は",
    "back": "つらぬきとめぬ玉ぞ散りける",
    "frontKana": "しらつゆにかせのふきしくあきののは",
    "backKana": "つらぬきとめぬたまそちりける",
    "imagefront": "",
    "imageBack": "",
    "audio": "Cardaudio2",
    "author": "文屋朝康",
    "theme": "秋",
    "kimarijiFront": 2,
    "kimarijiBack": 1
  },
  {
    "id": 38,
    "front": "忘らるる身をば思はず誓ひてし",
    "back": "人の命の惜しくもあるかな",
    "frontKana": "わすらるるみをばおもわずちかいてし",
    "backKana": "ひとのいのちのおしくもあるかな",
    "imagefront": "",
    "imageBack": "",
    "audio": "Cardaudio2",
    "author": "右近",
    "theme": "恋",
    "kimarijiFront": 3,
    "kimarijiBack": 3
  },
  {
    "id": 39,
    "front": "浅茅生の小野の篠原忍ぶれど",
    "back": "あまりてなどか人の恋しき",
    "frontKana": "あさちふのをののしのはらしのふれと",
    "backKana": "あまりてなとかひとのこひしき",
    "imagefront": "",
    "imageBack": "",
    "audio": "Cardaudio2",
    "author": "参議等",
    "theme": "恋",
    "kimarijiFront": 3,
    "kimarijiBack": 3
  },
  {
    "id": 40,
    "front": "忍ぶれど色に出でにけりわが恋は",
    "back": "ものや思ふと人の問ふまで",
    "frontKana": "しのふれといろにいてにけりわかこひは",
    "backKana": "ものやおもふとひとのとふまて",
    "imagefront": "",
    "imageBack": "",
    "audio": "Cardaudio2",
    "author": "平兼盛",
    "theme": "恋",
    "kimarijiFront": 2,
    "kimarijiBack": 2
  },
  {
    "id": 41,
    "front": "恋すてふわが名はまだき立ちにけり",
    "back": "人知れずこそ思ひそめしか",
    "frontKana": "こひすてふわかなはまたきたちにけり",
    "backKana": "ひとしれすこそおもひそめしか",
    "imagefront": "",
    "imageBack": "",
    "audio": "Cardaudio2",
    "author": "壬生忠見",
    "theme": "恋",
    "kimarijiFront": 2,
    "kimarijiBack": 3
  },
  {
    "id": 42,
    "front": "契りきなかたみに袖をしぼりつつ",
    "back": "末の松山波越さじとは",
    "frontKana": "ちきりきなかたみにそてをしほりつつ",
    "backKana": "すゑのまつやまなみこさしとは",
    "imagefront": "",
    "imageBack": "",
    "audio": "Cardaudio2",
    "author": "清原元輔",
    "theme": "恋",
    "kimarijiFront": 4,
    "kimarijiBack": 1
  },
  {
    "id": 43,
    "front": "逢ひ見てののちの心にくらぶれば",
    "back": "昔はものを思はざりけり",
    "frontKana": "あひみてののちのこころにくらふれは",
    "backKana": "むかしはものをおもはさりけり",
    "imagefront": "",
    "imageBack": "",
    "audio": "Cardaudio2",
    "author": "権中納言敦忠",
    "theme": "恋",
    "kimarijiFront": 2,
    "kimarijiBack": 2
  },
  {
    "id": 44,
    "front": "逢ふことの絶えてしなくはなかなかに",
    "back": "人をも身をも恨みざらまし",
    "frontKana": "あふことのたえてしなくはなかなかに",
    "backKana": "ひとをもみをもうらみさらまし",
    "imagefront": "",
    "imageBack": "",
    "audio": "Cardaudio2",
    "author": "中納言朝忠",
    "theme": "恋",
    "kimarijiFront": 3,
    "kimarijiBack": 3
  },
  {
    "id": 45,
    "front": "あはれともいふべき人は思ほえで",
    "back": "身のいたずらになりぬべきかな",
    "frontKana": "あはれともいふへきひとはおもほえて",
    "backKana": "みのいたつらになりぬへきかな",
    "imagefront": "",
    "imageBack": "",
    "audio": "Cardaudio2",
    "author": "謙徳公",
    "theme": "恋",
    "kimarijiFront": 3,
    "kimarijiBack": 2
  },
  {
    "id": 46,
    "front": "由良の門を渡る舟人かぢを絶え",
    "back": "ゆくへも知らぬ恋のみちかな",
    "frontKana": "ゆらのとをわたるふなひとかちをたえ",
    "backKana": "ゆくへもしらぬこひのみちかな",
    "imagefront": "",
    "imageBack": "",
    "audio": "Cardaudio2",
    "author": "曾禰好忠",
    "theme": "恋",
    "kimarijiFront": 2,
    "kimarijiBack": 2
  },
  {
    "id": 47,
    "front": "八重むぐら茂れる宿の寂しきに",
    "back": "人こそ見えね秋は来にけり",
    "frontKana": "やへむくらしけれるやとのさひしきに",
    "backKana": "ひとこそみえねあきはきにけり",
    "imagefront": "",
    "imageBack": "",
    "audio": "Cardaudio2",
    "author": "恵慶法師",
    "theme": "秋",
    "kimarijiFront": 2,
    "kimarijiBack": 5
  },
  {
    "id": 48,
    "front": "風をいたみ岩打つ波のおのれのみ",
    "back": "くだけてものを思ふころかな",
    "frontKana": "かせをいたみいはうつなみのおのれのみ",
    "backKana": "くたけてものをおもふころかな",
    "imagefront": "",
    "imageBack": "",
    "audio": "Cardaudio2",
    "author": "源重之",
    "theme": "恋",
    "kimarijiFront": 3,
    "kimarijiBack": 2
  },
  {
    "id": 49,
    "front": "御垣守衛士のたく火の夜は燃え",
    "back": "昼は消えつつものをこそ思へ",
    "frontKana": "みかきもりゑしのたくひのよるはもえ",
    "backKana": "ひるはきえつつものをこそおもへ",
    "imagefront": "",
    "imageBack": "",
    "audio": "Cardaudio2",
    "author": "大中臣能宣朝臣",
    "theme": "恋",
    "kimarijiFront": 3,
    "kimarijiBack": 2
  },
  {
    "id": 50,
    "front": "君がため惜しからざりし命さへ",
    "back": "長くもがなと思ひけるかな",
    "frontKana": "きみかためおしからさりしいのちさへ",
    "backKana": "なかくもかなとおもひけるかな",
    "imagefront": "",
    "imageBack": "",
    "audio": "Cardaudio2",
    "author": "藤原義孝",
    "theme": "恋",
    "kimarijiFront": 6,
    "kimarijiBack": 3
  },
  {
    "id": 51,
    "front": "かくとだにえやは伊吹のさしも草",
    "back": "さしも知らじな燃ゆる思ひを",
    "frontKana": "かくとたにえやはいふきのさしもくさ",
    "backKana": "さしもしらしなもゆるおもひを",
    "imagefront": "",
    "imageBack": "",
    "audio": "Cardaudio2",
    "author": "藤原実方朝臣",
    "theme": "恋",
    "kimarijiFront": 2,
    "kimarijiBack": 1
  },
  {
    "id": 52,
    "front": "明けぬれば暮るるものとは知りながら",
    "back": "なほ恨めしき朝ぼらけかな",
    "frontKana": "あけぬれはくるるものとはしりなから",
    "backKana": "なほうらめしきあさほらけかな",
    "imagefront": "",
    "imageBack": "",
    "audio": "Cardaudio2",
    "author": "藤原道信朝臣",
    "theme": "恋",
    "kimarijiFront": 2,
    "kimarijiBack": 3
  },
  {
    "id": 53,
    "front": "嘆きつつひとり寝る夜の明くる間は",
    "back": "いかに久しきものとかは知る",
    "frontKana": "なけきつつひとりぬるよのあくるまは",
    "backKana": "いかにひさしきものとかはしる",
    "imagefront": "",
    "imageBack": "",
    "audio": "Cardaudio2",
    "author": "右大将道綱母",
    "theme": "恋",
    "kimarijiFront": 3,
    "kimarijiBack": 2
  },
  {
    "id": 54,
    "front": "忘れじのゆく末まではかたければ",
    "back": "今日を限りの命ともがな",
    "frontKana": "わすれしのゆくすゑまてはかたけれは",
    "backKana": "けふをかきりのいのちともかな",
    "imagefront": "",
    "imageBack": "",
    "audio": "Cardaudio2",
    "author": "儀同三司母",
    "theme": "恋",
    "kimarijiFront": 3,
    "kimarijiBack": 2
  },
  {
    "id": 55,
    "front": "滝の音は絶えて久しくなりぬれど",
    "back": "名こそ流れてなほ聞こえけれ",
    "frontKana": "たきのおとはたえてひさしくなりぬれと",
    "backKana": "なこそなかれてなほきこえけれ",
    "imagefront": "",
    "imageBack": "",
    "audio": "Cardaudio2",
    "author": "大納言公任",
    "theme": "恋",
    "kimarijiFront": 2,
    "kimarijiBack": 2
  },
  {
    "id": 56,
    "front": "あらざらむこの世のほかの思ひ出に",
    "back": "いまひとたびの逢ふこともがな",
    "frontKana": "あらさらむこのよのほかのおもひてに",
    "backKana": "いまひとたひのあふこともかな",
    "imagefront": "",
    "imageBack": "",
    "audio": "Cardaudio2",
    "author": "和泉式部",
    "theme": "恋",
    "kimarijiFront": 3,
    "kimarijiBack": 8
  },
  {
    "id": 57,
    "front": "めぐり逢ひて見しやそれとも分かぬ間に",
    "back": "雲隠れにし夜半の月影",
    "frontKana": "めくりあひてみしやそれともわかぬまに",
    "backKana": "くもかくれにしよはのつきかけ",
    "imagefront": "",
    "imageBack": "",
    "audio": "Cardaudio2",
    "author": "紫式部",
    "theme": "雑",
    "kimarijiFront": 1,
    "kimarijiBack": 3
  },
  {
    "id": 58,
    "front": "有馬山猪名の篠原風吹けば",
    "back": "いでそよ人を忘れやはする",
    "frontKana": "ありまやまゐなのささはらかせふけは",
    "backKana": "いてそよひとをわすれやはする",
    "imagefront": "",
    "imageBack": "",
    "audio": "Cardaudio2",
    "author": "大弐三位",
    "theme": "恋",
    "kimarijiFront": 3,
    "kimarijiBack": 2
  },
  {
    "id": 59,
    "front": "やすらはで寝なましものをさ夜更けて",
    "back": "かたぶくまでの月を見しかな",
    "frontKana": "やすらはてねなましものをさよふけて",
    "backKana": "かたふくまてのつきをみしかな",
    "imagefront": "",
    "imageBack": "",
    "audio": "Cardaudio2",
    "author": "赤染衛門",
    "theme": "恋",
    "kimarijiFront": 2,
    "kimarijiBack": 2
  },
  {
    "id": 60,
    "front": "大江山いく野の道の遠ければ",
    "back": "まだふみも見ず天の橋立",
    "frontKana": "おほえやまいくののみちのとほけれは",
    "backKana": "またふみもみすあまのはしたて",
    "imagefront": "",
    "imageBack": "",
    "audio": "Cardaudio2",
    "author": "小式部内侍",
    "theme": "雑",
    "kimarijiFront": 3,
    "kimarijiBack": 2
  },
  {
    "id": 61,
    "front": "いにしへの奈良の都の八重桜",
    "back": "けふ九重に匂ひぬるかな",
    "frontKana": "いにしへのならのみやこのやへさくら",
    "backKana": "けふここのへににほひぬるかな",
    "imagefront": "",
    "imageBack": "",
    "audio": "Cardaudio2",
    "author": "伊勢大輔",
    "theme": "春",
    "kimarijiFront": 2,
    "kimarijiBack": 3
  },
  {
    "id": 62,
    "front": "夜をこめて鳥のそら音ははかるとも",
    "back": "よに逢坂の関は許さじ",
    "frontKana": "よをこめてとりのそらねははかるとも",
    "backKana": "よにあふさかのせきはゆるさし",
    "imagefront": "",
    "imageBack": "",
    "audio": "Cardaudio2",
    "author": "清少納言",
    "theme": "雑",
    "kimarijiFront": 2,
    "kimarijiBack": 2
  },
  {
    "id": 63,
    "front": "今はただ思ひ絶えなむとばかりを",
    "back": "人づてならでいふよしもがな",
    "frontKana": "いまはたたおもひたえなむとはかりを",
    "backKana": "ひとつてならていふよしもかな",
    "imagefront": "",
    "imageBack": "",
    "audio": "Cardaudio2",
    "author": "左京大夫道雅",
    "theme": "恋",
    "kimarijiFront": 3,
    "kimarijiBack": 3
  },
  {
    "id": 64,
    "front": "朝ぼらけ宇治の川霧たえだえに",
    "back": "あらはれわたる瀬々の網代木",
    "frontKana": "あさほらけうちのかはきりたえたえに",
    "backKana": "あらはれわたるせせのあしろき",
    "imagefront": "",
    "imageBack": "",
    "audio": "Cardaudio2",
    "author": "権中納言定頼",
    "theme": "冬",
    "kimarijiFront": 6,
    "kimarijiBack": 2
  },
  {
    "id": 65,
    "front": "恨みわび干さぬ袖だにあるものを",
    "back": "恋に朽ちなむ名こそ惜しけれ",
    "frontKana": "うらみわひほさぬそてたにあるものを",
    "backKana": "こひにくちなむなこそをしけれ",
    "imagefront": "",
    "imageBack": "",
    "audio": "Cardaudio2",
    "author": "相模",
    "theme": "恋",
    "kimarijiFront": 2,
    "kimarijiBack": 3
  },
  {
    "id": 66,
    "front": "もろともにあはれと思え山桜",
    "back": "花よりほかに知る人もなし",
    "frontKana": "もろともにあはれとおもへやまさくら",
    "backKana": "はなよりほかにしるひともなし",
    "imagefront": "",
    "imageBack": "",
    "audio": "Cardaudio2",
    "author": "前大僧正行尊",
    "theme": "雑",
    "kimarijiFront": 2,
    "kimarijiBack": 3
  },
  {
    "id": 67,
    "front": "春の夜の夢ばかりなる手枕に",
    "back": "かひなく立たむ名こそをしけれ",
    "frontKana": "はるのよのゆめはかりなるたまくらに",
    "backKana": "かひなくたたむなこそをしけれ",
    "imagefront": "",
    "imageBack": "",
    "audio": "Cardaudio2",
    "author": "周防内侍",
    "theme": "春",
    "kimarijiFront": 3,
    "kimarijiBack": 2
  },
  {
    "id": 68,
    "front": "心にもあらで憂き夜に長らへば",
    "back": "恋しかるべき夜半の月かな",
    "frontKana": "こころにもあらてうきよになからへは",
    "backKana": "こひしかるへきよはのつきかな",
    "imagefront": "",
    "imageBack": "",
    "audio": "Cardaudio2",
    "author": "三条院",
    "theme": "雑",
    "kimarijiFront": 4,
    "kimarijiBack": 3
  },
  {
    "id": 69,
    "front": "嵐吹く三室の山のもみぢ葉は",
    "back": "竜田の川の錦なりけり",
    "frontKana": "あらしふくみむろのやまのもみちはは",
    "backKana": "たつたのかはのにしきなりけり",
    "imagefront": "",
    "imageBack": "",
    "audio": "Cardaudio2",
    "author": "能因法師",
    "theme": "秋",
    "kimarijiFront": 3,
    "kimarijiBack": 2
  },
  {
    "id": 70,
    "front": "寂しさに宿を立ち出でてながむれば",
    "back": "いづくも同じ秋の夕暮れ",
    "frontKana": "さひしさにやとをたちいててなかむれは",
    "backKana": "いつくもおなしあきのゆふくれ",
    "imagefront": "",
    "imageBack": "",
    "audio": "Cardaudio2",
    "author": "良暹法師",
    "theme": "秋",
    "kimarijiFront": 1,
    "kimarijiBack": 3
  },
  {
    "id": 71,
    "front": "夕されば門田の稲葉訪れて",
    "back": "蘆のまろ屋に秋風ぞ吹く",
    "frontKana": "ゆうされはかとたのいなはおとつれて",
    "backKana": "あしのまろやにあきかせそふく",
    "imagefront": "",
    "imageBack": "",
    "audio": "Cardaudio2",
    "author": "大納言経信",
    "theme": "秋",
    "kimarijiFront": 2,
    "kimarijiBack": 2
  },
  {
    "id": 72,
    "front": "音に聞く高師の浜のあだ波は",
    "back": "かけじや袖のぬれもこそすれ",
    "frontKana": "おとにきくたかしのはまのあたなみは",
    "backKana": "かけしやそてのぬれもこそすれ",
    "imagefront": "",
    "imageBack": "",
    "audio": "Cardaudio2",
    "author": "祐子内親王家紀伊",
    "theme": "恋",
    "kimarijiFront": 2,
    "kimarijiBack": 2
  },
  {
    "id": 73,
    "front": "高砂の尾の上の桜咲きにけり",
    "back": "外山のかすみ立たずもあらなむ",
    "frontKana": "たかさこのをのへのさくらさきにけり",
    "backKana": "とやまのかすみたたすもあらなむ",
    "imagefront": "",
    "imageBack": "",
    "audio": "Cardaudio2",
    "author": "前権中納言匡房",
    "theme": "春",
    "kimarijiFront": 2,
    "kimarijiBack": 1
  },
  {
    "id": 74,
    "front": "憂かりける人を初瀬の山おろしよ",
    "back": "激しかれとは祈らぬものを",
    "frontKana": "うかりけるひとをはつせのやまおろしよ",
    "backKana": "はけしかれとはいのらぬものを",
    "imagefront": "",
    "imageBack": "",
    "audio": "Cardaudio2",
    "author": "源俊頼朝臣",
    "theme": "恋",
    "kimarijiFront": 2,
    "kimarijiBack": 2
  },
  {
    "id": 75,
    "front": "契りおきしさせもが露を命にて",
    "back": "あはれ今年の秋もいぬめり",
    "frontKana": "ちきりおきしさせもかつゆをいのちにて",
    "backKana": "あはれことしのあきもいぬめり",
    "imagefront": "",
    "imageBack": "",
    "audio": "Cardaudio2",
    "author": "藤原基俊",
    "theme": "雑",
    "kimarijiFront": 4,
    "kimarijiBack": 4
  },
  {
    "id": 76,
    "front": "わたの原漕ぎ出でて見ればひさかたの",
    "back": "雲居にまがふ沖つ白波",
    "frontKana": "わたのはらこきいててみれはひさかたの",
    "backKana": "くもゐにまかふおきつしらなみ",
    "imagefront": "",
    "imageBack": "",
    "audio": "Cardaudio2",
    "author": "	法性寺入道前関白太政大臣",
    "theme": "雑",
    "kimarijiFront": 6,
    "kimarijiBack": 3
  },
  {
    "id": 77,
    "front": "瀬をはやみ岩にせかるる滝川の",
    "back": "われても末に逢はむとぞ思ふ",
    "frontKana": "せをはやみいわにせかるるたきかはの",
    "backKana": "われてもすゑにあはむとそおもふ",
    "imagefront": "",
    "imageBack": "",
    "audio": "Cardaudio2",
    "author": "崇徳院",
    "theme": "恋",
    "kimarijiFront": 1,
    "kimarijiBack": 2
  },
  {
    "id": 78,
    "front": "淡路島通ふ千鳥の鳴く声に",
    "back": "いく夜寝覚めぬ須磨の関守",
    "frontKana": "あはちしまかよふちとりのなくこゑに",
    "backKana": "いくよねさめぬすまのせきもり",
    "imagefront": "",
    "imageBack": "",
    "audio": "Cardaudio2",
    "author": "源兼昌",
    "theme": "冬",
    "kimarijiFront": 3,
    "kimarijiBack": 2
  },
  {
    "id": 79,
    "front": "秋風にたなびく雲のたえ間より",
    "back": "漏れ出づる月の影のさやけさ",
    "frontKana": "あきかせにたなひくくものたえまより",
    "backKana": "もれいつるつきのかけのさやけさ",
    "imagefront": "",
    "imageBack": "",
    "audio": "Cardaudio2",
    "author": "左京大夫顕輔",
    "theme": "秋",
    "kimarijiFront": 3,
    "kimarijiBack": 2
  },
  {
    "id": 80,
    "front": "ながからむ心も知らず黒髪の",
    "back": "乱れてけさはものをこそ思へ",
    "frontKana": "なかからむこころもしらすくろかみの",
    "backKana": "みたれてけさはものをこそおもへ",
    "imagefront": "",
    "imageBack": "",
    "audio": "Cardaudio2",
    "author": "待賢門院堀河",
    "theme": "恋",
    "kimarijiFront": 3,
    "kimarijiBack": 4
  },
  {
    "id": 81,
    "front": "ほととぎす鳴きつる方をながむれば",
    "back": "ただ有明の月ぞ残れる",
    "frontKana": "ほとときすなきつるかたをなかむれは",
    "backKana": "たたありあけのつきそのこれる",
    "imagefront": "",
    "imageBack": "",
    "audio": "Cardaudio2",
    "author": "後徳大寺左大臣",
    "theme": "夏",
    "kimarijiFront": 1,
    "kimarijiBack": 2
  },
  {
    "id": 82,
    "front": "思ひわびさても命はあるものを",
    "back": "憂きに堪へぬは涙なりけり",
    "frontKana": "おもひわひさてもいのちはあるものを",
    "backKana": "うきにたへぬはなみたなりけり",
    "imagefront": "",
    "imageBack": "",
    "audio": "Cardaudio2",
    "author": "道因法師",
    "theme": "恋",
    "kimarijiFront": 2,
    "kimarijiBack": 2
  },
  {
    "id": 83,
    "front": "世の中よ道こそなけれ思ひ入る",
    "back": "山の奥にも鹿ぞ鳴くなる",
    "frontKana": "よのなかよみちこそなけれおもひいる",
    "backKana": "やまのおくにもしかそなくなる",
    "imagefront": "",
    "imageBack": "",
    "audio": "Cardaudio2",
    "author": "皇太后宮大夫俊成",
    "theme": "雑",
    "kimarijiFront": 5,
    "kimarijiBack": 2
  },
  {
    "id": 84,
    "front": "長らへばまたこのごろやしのばれむ",
    "back": "憂しと見し世ぞ今は恋しき",
    "frontKana": "なからへはまたこのころやしのはれむ",
    "backKana": "うしとみしよそいまはこひしき",
    "imagefront": "",
    "imageBack": "",
    "audio": "Cardaudio2",
    "author": "藤原清輔朝臣",
    "theme": "雑",
    "kimarijiFront": 3,
    "kimarijiBack": 2
  },
  {
    "id": 85,
    "front": "夜もすがらもの思ふころは明けやらぬ",
    "back": "ねやのひまさへつれなかりけり",
    "frontKana": "よもすからものおもふころはあけやらぬ",
    "backKana": "ねやのひまさへつれなかりけり",
    "imagefront": "",
    "imageBack": "",
    "audio": "Cardaudio2",
    "author": "俊恵法師",
    "theme": "恋",
    "kimarijiFront": 2,
    "kimarijiBack": 1
  },
  {
    "id": 86,
    "front": "嘆けとて月やはものを思はする",
    "back": "かこちがほなるわが涙かな",
    "frontKana": "なけけとてつきやはものをおもはする",
    "backKana": "かこちかほなるわかなみたかな",
    "imagefront": "",
    "imageBack": "",
    "audio": "Cardaudio2",
    "author": "	西行法師",
    "theme": "恋",
    "kimarijiFront": 3,
    "kimarijiBack": 2
  },
  {
    "id": 87,
    "front": "村雨の露もまだ干ぬまきの葉に",
    "back": "霧立ちのぼる秋の夕暮",
    "frontKana": "むらさめのつゆもまたひぬまきのはに",
    "backKana": "きりたちのほるあきのゆふくれ",
    "imagefront": "",
    "imageBack": "",
    "audio": "Cardaudio2",
    "author": "寂蓮法師",
    "theme": "秋",
    "kimarijiFront": 1,
    "kimarijiBack": 2
  },
  {
    "id": 88,
    "front": "難波江の蘆のかりねのひとよゆゑ",
    "back": "身を尽くしてや恋ひわたるべき",
    "frontKana": "なにはえのあしのかりねのひとよゆゑ",
    "backKana": "みをつくしてやこひわたるへき",
    "imagefront": "",
    "imageBack": "",
    "audio": "Cardaudio2",
    "author": "皇嘉門院別当",
    "theme": "恋",
    "kimarijiFront": 4,
    "kimarijiBack": 7
  },
  {
    "id": 89,
    "front": "玉の緒よ絶えなば絶えねながらへば",
    "back": "忍ぶることの弱りもぞする",
    "frontKana": "たまのをよたえなはたえねなからへは",
    "backKana": "しのふることのよはりもそする",
    "imagefront": "",
    "imageBack": "",
    "audio": "Cardaudio2",
    "author": "式子内親王",
    "theme": "恋",
    "kimarijiFront": 2,
    "kimarijiBack": 2
  },
  {
    "id": 90,
    "front": "見せばやな雄島の海人の袖だにも",
    "back": "濡れにぞ濡れし色は変はらず",
    "frontKana": "みせはやなをしまのあまのそてたにも",
    "backKana": "ぬれにそぬれしいろはかはらす",
    "imagefront": "",
    "imageBack": "",
    "audio": "Cardaudio2",
    "author": "殷富門院大輔",
    "theme": "恋",
    "kimarijiFront": 2,
    "kimarijiBack": 1
  },
  {
    "id": 91,
    "front": "きりぎりす鳴くや霜夜のさむしろに",
    "back": "衣かたしきひとりかも寝む",
    "frontKana": "きりきりすなくやしもよのさむしろに",
    "backKana": "ころもかたしきひとりかもねむ",
    "imagefront": "",
    "imageBack": "",
    "audio": "Cardaudio2",
    "author": "後京極摂政前太政大臣",
    "theme": "秋",
    "kimarijiFront": 2,
    "kimarijiBack": 4
  },
  {
    "id": 92,
    "front": "わが袖は潮干に見えぬ沖の石の",
    "back": "人こそ知らねかわく間もなし",
    "frontKana": "わかそてはしほひにみえぬおきのいしの",
    "backKana": "ひとこそしらねかわくまもなし",
    "imagefront": "",
    "imageBack": "",
    "audio": "Cardaudio2",
    "author": "二条院讃岐",
    "theme": "恋",
    "kimarijiFront": 3,
    "kimarijiBack": 5
  },
  {
    "id": 93,
    "front": "世の中は常にもがもな渚漕ぐ",
    "back": "海人の小舟の綱手かなしも",
    "frontKana": "よのなかはつねにもかもななきさこく",
    "backKana": "あまのおふねのつなてかなしも",
    "imagefront": "",
    "imageBack": "",
    "audio": "Cardaudio2",
    "author": "鎌倉右大臣",
    "theme": "羇旅",
    "kimarijiFront": 5,
    "kimarijiBack": 3
  },
  {
    "id": 94,
    "front": "み吉野の山の秋風さよ更けて",
    "back": "ふるさと寒く衣打つなり",
    "frontKana": "みよしののやまのあきかせさよふけて",
    "backKana": "ふるさとさむくころもうつなり",
    "imagefront": "",
    "imageBack": "",
    "audio": "Cardaudio2",
    "author": "参議雅経",
    "theme": "秋",
    "kimarijiFront": 2,
    "kimarijiBack": 2
  },
  {
    "id": 95,
    "front": "おほけなく憂き世の民におほふかな",
    "back": "わが立つ杣にすみ染の袖",
    "frontKana": "おほけなくうきよのたみにおほふかな",
    "backKana": "わかたつそまにすみそめのそて",
    "imagefront": "",
    "imageBack": "",
    "audio": "Cardaudio2",
    "author": "前大僧正慈円",
    "theme": "雑",
    "kimarijiFront": 3,
    "kimarijiBack": 3
  },
  {
    "id": 96,
    "front": "花さそふ嵐の庭の雪ならで",
    "back": "ふりゆくものはわが身なりけり",
    "frontKana": "はなさそふあらしのにはのゆきならて",
    "backKana": "ふりゆくものはわかみなりけり",
    "imagefront": "",
    "imageBack": "",
    "audio": "Cardaudio2",
    "author": "花誘うふり",
    "theme": "雑",
    "kimarijiFront": 3,
    "kimarijiBack": 2
  },
  {
    "id": 97,
    "front": "来ぬ人を松帆の浦の夕なぎに",
    "back": "焼くや藻塩の身もこがれつつ",
    "frontKana": "こぬひとをまつほのうらのゆふなきに",
    "backKana": "やくやもしほのみもこかれつつ",
    "imagefront": "",
    "imageBack": "",
    "audio": "Cardaudio2",
    "author": "権中納言定家",
    "theme": "恋",
    "kimarijiFront": 2,
    "kimarijiBack": 2
  },
  {
    "id": 98,
    "front": "風そよぐ楢の小川の夕暮は",
    "back": "御禊ぞ夏のしるしなりける",
    "frontKana": "かせそよくならのをかはのゆふくれは",
    "backKana": "みそきそなつのしるしなりける",
    "imagefront": "",
    "imageBack": "",
    "audio": "Cardaudio2",
    "author": "従二位家隆",
    "theme": "夏",
    "kimarijiFront": 3,
    "kimarijiBack": 2
  },
  {
    "id": 99,
    "front": "人も愛し人も恨めしあじきなく",
    "back": "世を思ふゆゑにもの思ふ身は",
    "frontKana": "ひともをしひともうらめしあちきなく",
    "backKana": "よをおもふゆゑにものおもふみは",
    "imagefront": "",
    "imageBack": "",
    "audio": "Cardaudio2",
    "author": "後鳥羽院",
    "theme": "雑",
    "kimarijiFront": 3,
    "kimarijiBack": 3
  },
  {
    "id": 100,
    "front": "百敷や古き軒端のしのぶにも",
    "back": "なほ余りある昔なりけり",
    "frontKana": "ももしきやふるきのきはのしのふにも",
    "backKana": "なほあまりあるむかしなりけり",
    "imagefront": "",
    "imageBack": "",
    "audio": "Cardaudio2",
    "author": "順徳院",
    "theme": "雑",
    "kimarijiFront": 2,
    "kimarijiBack": 2
  },
]